name: Docker image cleanup

on:
  schedule:
    - cron: "42 2 * * 0" # Run every Sunday at 02:42 UTC.
  workflow_dispatch:

jobs:
  cleanup:
    runs-on: ubuntu-latest
    permissions:
      packages: write
    strategy:
        fail-fast: false
        matrix:
          image:
            - debian-bullseye
            - debian-bookworm
            - debian-gcc
            - rhel-9.4
            - rhel-9.6
            - tools-rippled-clang-format
            - tools-rippled-documentation
            - tools-rippled-pre-commit
            - tools-rippled-prettier
            - ubuntu-jammy
            - ubuntu-noble
    steps:
      - name: Cleanup images in the GitHub Container Registry
        uses: dataaxiom/ghcr-cleanup-action@v1
        with:
          delete-ghost-images: true
          delete-orphaned-images: true
          delete-partial-images: true
          delete-untagged: true
          package: ci/${{ matrix.image }}
