name: Debian

on:
  push:
    paths:
      - .github/workflows/debian.yml
      - docker/debian/Dockerfile

env:
  CONTAINER_REGISTRY: ghcr.io
  DOCKER_BUILDKIT: 1
  BUILDKIT_PROGRESS: plain
  CONAN_VERSION: 2.17.0
  NONROOT_USER: ci

jobs:
  # Build the Docker image for Debian using different versions of GCC.
  gcc:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        version:
          - os: bookworm
            gcc: 12
          - os: bookworm
            gcc: 13
          - os: bookworm
            gcc: 14
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Login to GitHub Registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.CONTAINER_REGISTRY }}
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN  }}
      - name: Determine the Docker image name.
        run: |
          # Convert the repository name to lowercase as the organization name is
          # uppercase, which is not permitted by the Docker registry.
          GITHUB_REPO=${{ github.repository }}
          CONTAINER_REPOSITORY=${GITHUB_REPO@L}
          echo "CONTAINER_IMAGE=${CONTAINER_REGISTRY}/${CONTAINER_REPOSITORY}/debian-${{ matrix.version.os }}:gcc${{ matrix.version.gcc }}" >> $GITHUB_ENV
      - name: Build and push the Docker image
        uses: docker/build-push-action@v6
        with:
          build-args: |
            BUILDKIT_DOCKERFILE_CHECK=skip=InvalidDefaultArgInFrom
            BUILDKIT_INLINE_CACHE=1
            CONAN_VERSION=${{ env.CONAN_VERSION }}
            DEBIAN_VERSION=${{ matrix.version.os }}
            GCC_VERSION=${{ matrix.version.gcc }}
            GITHUB_REPO=${{ github.repository }}
            NONROOT_USER=${{ env.NONROOT_USER }}
          context: docker/debian
          platforms: linux/amd64,linux/arm64
          push: true
          tags: ${{ env.CONTAINER_IMAGE }}
          target: gcc

  # Build the Docker image for Debian using different versions of Clang.
  clang:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        version:
          - os: bookworm
            clang: 16
          - os: bookworm
            clang: 17
          - os: bookworm
            clang: 18
          - os: bookworm
            clang: 19
          - os: bookworm
            clang: 20
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Login to GitHub Registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.CONTAINER_REGISTRY }}
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN  }}
      - name: Determine the Docker image name.
        run: |
          # Convert the repository name to lowercase as the organization name is
          # uppercase, which is not permitted by the Docker registry.
          GITHUB_REPO=${{ github.repository }}
          CONTAINER_REPOSITORY=${GITHUB_REPO@L}
          echo "CONTAINER_IMAGE=${CONTAINER_REGISTRY}/${CONTAINER_REPOSITORY}/debian-${{ matrix.version.os }}:clang${{ matrix.version.clang }}" >> $GITHUB_ENV
      - name: Build and push the Docker image
        uses: docker/build-push-action@v6
        with:
          build-args: |
            BUILDKIT_DOCKERFILE_CHECK=skip=InvalidDefaultArgInFrom
            BUILDKIT_INLINE_CACHE=1
            CLANG_VERSION=${{ matrix.version.clang }}
            CONAN_VERSION=${{ env.CONAN_VERSION }}
            DEBIAN_VERSION=${{ matrix.version.os }}
            GITHUB_REPO=${{ github.repository }}
            NONROOT_USER=${{ env.NONROOT_USER }}
          context: docker/debian
          platforms: linux/amd64,linux/arm64
          push: true
          tags: ${{ env.CONTAINER_IMAGE }}
          target: clang
