name: RHEL

on:
  push:
    paths:
      - .github/workflows/rhel.yml
      - docker/rhel/Dockerfile

env:
  CONTAINER_REGISTRY: ghcr.io
  REDHAT_REGISTRY: registry.redhat.io
  DOCKER_BUILDKIT: 1
  BUILDKIT_PROGRESS: plain
  CONAN_VERSION: 2.17.0
  NONROOT_USER: ci

jobs:
  # Build the Docker image for Red Hat Enterprise Linux using different versions
  # of GCC and Clang.
  gcc:
    strategy:
      matrix:
        architecture:
          - platform: linux/amd64
            runner: ubuntu-24.04
          - platform: linux/arm64
            runner: ubuntu-24.04-arm
        os:
          - release: 9.6
            compiler_name: gcc
            compiler_version: 13
          - release: 9.6
            compiler_name: gcc
            compiler_version: 14
          - release: 9.6
            compiler_name: clang
            compiler_version: ''
    runs-on: ${{ matrix.architecture.runner }}
    permissions:
      packages: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Login to GitHub Registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.CONTAINER_REGISTRY }}
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN  }}
      - name: Login to Red Hat Registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REDHAT_REGISTRY }}
          username: ${{ secrets.REDHAT_USER }}
          password: ${{ secrets.REDHAT_TOKEN }}
      - name: Determine the Docker image name.
        run: |
          # Convert the repository name to lowercase as the organization name is
          # uppercase, which is not permitted by the Docker registry. It's 2025 and GitHub
          # still does not provide convenient action expression syntax for lowercase.
          GITHUB_REPO=${{ github.repository }}
          CONTAINER_REPO=${GITHUB_REPO@L}
          echo "CONTAINER_REPOSITORY=${CONTAINER_REPO}/rhel-${{ matrix.os.release }}" >> $GITHUB_ENV
          echo "CONTAINER_IMAGE=${CONTAINER_REGISTRY}/${CONTAINER_REPO}/rhel-${{ matrix.os.release }}" >> $GITHUB_ENV
      - name: Prepare container metadata
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.CONTAINER_IMAGE }}
          tags: |
            type=raw,value=${{ matrix.os.compiler_name }}-${{ matrix.os.compiler_version }}
            type=sha,prefix=${{ matrix.os.compiler_name }}-${{ matrix.os.compiler_version }}-sha-
          labels: |
            org.opencontainers.image.authors=For inquiries, please use https://github.com/XRPLF/ci/issues
            org.opencontainers.image.documentation=https://github.com/XRPLF/ci
            org.opencontainers.image.vendor=XRPLF
            org.opencontainers.image.title=${{ env.CONTAINER_REPOSITORY }}
      - name: Build and push the Docker image
        uses: docker/build-push-action@v6
        with:
          build-args: |
            BUILDKIT_DOCKERFILE_CHECK=skip=InvalidDefaultArgInFrom
            BUILDKIT_INLINE_CACHE=1
            CONAN_VERSION=${{ env.CONAN_VERSION }}
            GCC_VERSION=${{ matrix.os.compiler_name == 'gcc' && matrix.os.compiler_version || '' }}
            GITHUB_REPO=${{ github.repository }}
            NONROOT_USER=${{ env.NONROOT_USER }}
            RHEL_VERSION=${{ matrix.os.release }}
          context: docker/rhel
          outputs: type=image,name=${{ env.CONTAINER_IMAGE }},push-by-digest=true,name-canonical=true,push=true
          platforms: ${{ matrix.architecture.platform }}
          provenance: mode=max
          push: ${{ github.event_name != 'pull_request' }}
          sbom: true
          labels: ${{ steps.meta.outputs.labels }}
          target: ${{ matrix.os.compiler_name }}
