name: Tools-rippled

on:
  push:
    paths:
      - .github/workflows/tools-rippled.yml
      - docker/tools-rippled/Dockerfile

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

defaults:
  run:
    shell: bash

env:
  CONTAINER_REGISTRY: ghcr.io
  BUILDKIT_PROGRESS: plain
  CLANG_FORMAT_VERSION: 18.1.8
  PRE_COMMIT_VERSION: 4.2.0
  DOXYGEN_VERSION: 1.9.8+ds-2build5
  GRAPHVIZ_VERSION: 2.42.2-9ubuntu0.1
  UBUNTU_VERSION: noble

jobs:
  build:
    strategy:
      matrix:
        architecture:
          - platform: linux/amd64
            runner: ubuntu-24.04
          - platform: linux/arm64
            runner: ubuntu-24.04-arm
        tool:
          - clang-format
          - documentation
    runs-on: ${{ matrix.architecture.runner }}
    permissions:
      packages: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Login to GitHub Registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.CONTAINER_REGISTRY }}
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN  }}
      - name: Prepare environment
        run: |
          # Convert the repository name to lowercase as the organization name is
          # uppercase, which is not permitted by the Docker registry. It's 2025 and GitHub
          # still does not provide convenient action expression syntax for lowercase.
          GITHUB_REPO=${{ github.repository }}
          CONTAINER_REPO=${GITHUB_REPO@L}
          echo "CONTAINER_REPOSITORY=${CONTAINER_REPO}/tools-rippled-${{ matrix.tool }}" >> $GITHUB_ENV
          echo "CONTAINER_IMAGE=${CONTAINER_REGISTRY}/${CONTAINER_REPO}/tools-rippled-${{ matrix.tool }}" >> $GITHUB_ENV
          PLATFORM=${{ matrix.architecture.platform }}
          echo "PLATFORM_PAIR=${PLATFORM//\//-}" >> $GITHUB_ENV
      - name: Prepare container metadata
        id: meta
        uses: docker/metadata-action@v5
        env:
          DOCKER_METADATA_ANNOTATIONS_LEVELS: manifest,manifest-descriptor
        with:
          images: ${{ env.CONTAINER_IMAGE }}
          tags: |
            type=sha,prefix=sha-
            type=raw,value=latest
          labels: |
            org.opencontainers.image.authors=For inquiries, please use https://${{ github.repository }}/issues
            org.opencontainers.image.documentation=https://${{ github.repository }}
            org.opencontainers.image.vendor=XRPLF
            org.opencontainers.image.title=${{ env.CONTAINER_REPOSITORY }}
      - name: Build and push the Docker image
        id: build
        uses: docker/build-push-action@v6
        with:
          build-args: |
            BUILDKIT_DOCKERFILE_CHECK=skip=InvalidDefaultArgInFrom
            BUILDKIT_INLINE_CACHE=1
            UBUNTU_VERSION=${{ env.UBUNTU_VERSION }}
            CLANG_FORMAT_VERSION=${{ env.CLANG_FORMAT_VERSION }}
            PRE_COMMIT_VERSION=${{ env.PRE_COMMIT_VERSION }}
            DOXYGEN_VERSION=${{ env.DOXYGEN_VERSION }}
            GRAPHVIZ_VERSION=${{ env.GRAPHVIZ_VERSION }}
          context: docker/tools-rippled
          outputs: type=image,name=${{ env.CONTAINER_IMAGE }},push-by-digest=true,name-canonical=true,push=true
          platforms: ${{ matrix.architecture.platform }}
          provenance: mode=max
          push: ${{ github.ref_type == 'branch' && github.ref_name == github.event.repository.default_branch }}
          sbom: true
          labels: ${{ steps.meta.outputs.labels }}
          target: ${{ matrix.tool }}
      - name: Export digest
        if: ${{ github.ref_type == 'branch' && github.ref_name == github.event.repository.default_branch }}
        run: |
          mkdir -p /tmp/digests
          DIGEST="${{ steps.build.outputs.digest }}"
          touch "/tmp/digests/${DIGEST#sha256:}"
      - name: Upload digest
        if: ${{ github.ref_type == 'branch' && github.ref_name == github.event.repository.default_branch }}
        uses: actions/upload-artifact@v4
        with:
          name: digests-${{ matrix.tool }}-${{ env.PLATFORM_PAIR }}
          path: /tmp/digests/*
          if-no-files-found: error
          retention-days: 1

  merge:
    if: ${{ github.ref_type == 'branch' && github.ref_name == github.event.repository.default_branch }}
    strategy:
      matrix:
        tool:
          - clang-format
          - documentation
    runs-on: ubuntu-24.04
    needs:
      - build
    permissions:
      packages: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Download digests
        uses: actions/download-artifact@v4
        with:
          path: /tmp/digests
          pattern: digests-${{ matrix.tool }}-*
          merge-multiple: true
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Login to GitHub Registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.CONTAINER_REGISTRY }}
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN  }}
      - name: Prepare environment
        run: |
          GITHUB_REPO=${{ github.repository }}
          CONTAINER_REPO=${GITHUB_REPO@L}
          echo "CONTAINER_IMAGE=${CONTAINER_REGISTRY}/${CONTAINER_REPO}/tools-rippled-${{ matrix.tool }}" >> $GITHUB_ENV
      - name: Prepare container metadata
        id: meta
        uses: docker/metadata-action@v5
        env:
          DOCKER_METADATA_ANNOTATIONS_LEVELS: index
        with:
          images: ${{ env.CONTAINER_IMAGE }}
          tags: |
            type=sha,prefix=sha-
            type=raw,value=latest
      - name: Create manifest list and push
        working-directory: /tmp/digests
        run: |
          eval "docker buildx imagetools create \
            $(jq -cr '.tags | map("-t " + .) | join(" ")' <<< "$DOCKER_METADATA_OUTPUT_JSON") \
            $(jq -cr '.annotations | map("--annotation \"" + . + "\"") | join(" ")' <<< "$DOCKER_METADATA_OUTPUT_JSON") \
            $(printf '${{ env.CONTAINER_IMAGE }}@sha256:%s ' *)"
      - name: Inspect image
        run: |
          docker buildx imagetools inspect ${{ env.CONTAINER_IMAGE }}:${{ steps.meta.outputs.version }}
