name: Ubuntu

on:
  push:

env:
  DOCKER_REGISTRY: ghcr.io

jobs:
  # Build the Docker image for Ubuntu using different versions of GCC.
  gcc:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        version:
          - os: jammy
            gcc: 12
          - os: noble
            gcc: 14
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Login to GitHub Container Registry
        run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ${DOCKER_REGISTRY} -u ${{ github.actor }} --password-stdin
      - name: Build the Docker image
        working-directory: docker/ubuntu
        run: |
          DOCKER_BUILDKIT=1 docker build . \
          --target gcc \
          --build-arg UBUNTU_VERSION=${{ matrix.version.os }} \
          --build-arg GCC_VERSION=${{ matrix.version.gcc }} \
          --tag ${{ github.event.repository.name }}/${{ matrix.version.os }}:gcc${{ matrix.version.gcc }}

  # Build the Docker image for Ubuntu using different versions of Clang.
  clang:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        version:
          - os: noble
            clang: 18
          - os: noble
            clang: 19
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Login to GitHub Container Registry
        run: |
          run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ${DOCKER_REGISTRY} -u ${{ github.actor }} --password-stdin
      - name: Build the Docker image
        working-directory: docker/ubuntu
        run: |
          DOCKER_BUILDKIT=1 docker build . \
          --target clang \
          --build-arg UBUNTU_VERSION=${{ matrix.version.os }} \
          --build-arg CLANG_VERSION=${{ matrix.version.clang }} \
          --tag ${{ github.event.repository.name }}/${{ matrix.version.os }}:clang{{ matrix.version.clang }}
