name: Ubuntu

on:
  push:
    paths:
      - .github/workflows/ubuntu.yml
      - docker/ubuntu/Dockerfile

env:
  CONTAINER_REGISTRY: ghcr.io
  DOCKER_BUILDKIT: 1
  BUILDKIT_PROGRESS: plain
  CONAN_VERSION: 2.17.0
  NONROOT_USER: ci

jobs:
  # Build the Docker image for Ubuntu using different versions of GCC and Clang.
  # See https://documentation.ubuntu.com/ubuntu-for-developers/reference/availability/gcc/.
  gcc:
    strategy:
      matrix:
        architecture:
          - platform: linux/amd64
            runner: ubuntu-24.04
          - platform: linux/arm64
            runner: ubuntu-24.04-arm
        os:
          - distro: jammy
            compiler_name: gcc
            compiler_version: 12
          - distro: noble
            compiler_name: gcc
            compiler_version: 13
          - distro: noble
            compiler_name: gcc
            compiler_version: 14
          - distro: noble
            compiler_name: clang
            compiler_version: 16
          - distro: noble
            compiler_name: clang
            compiler_version: 17
          - distro: noble
            compiler_name: clang
            compiler_version: 18
          - distro: noble
            compiler_name: clang
            compiler_version: 19
    runs-on: ${{ matrix.architecture.runner }}
    permissions:
      packages: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Login to GitHub Registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.CONTAINER_REGISTRY }}
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN  }}
      - name: Determine the Docker image name.
        run: |
          # Convert the repository name to lowercase as the organization name is
          # uppercase, which is not permitted by the Docker registry.
          GITHUB_REPO=${{ github.repository }}
          CONTAINER_REPOSITORY=${GITHUB_REPO@L}
          echo "CONTAINER_IMAGE=${CONTAINER_REGISTRY}/${CONTAINER_REPOSITORY}/ubuntu-${{ matrix.os.distro }}:${{ matrix.os.compiler_name }}${{ matrix.os.compiler_version }}" >> $GITHUB_ENV
      - name: Build and push the Docker image
        uses: docker/build-push-action@v6
        with:
          build-args: |
            BUILDKIT_DOCKERFILE_CHECK=skip=InvalidDefaultArgInFrom
            BUILDKIT_INLINE_CACHE=1
            CLANG_VERSION=${{ matrix.os.compiler_name == 'clang' && matrix.os.compiler_version || '' }}
            CONAN_VERSION=${{ env.CONAN_VERSION }}
            GCC_VERSION=${{ matrix.os.compiler_name == 'gcc' && matrix.os.compiler_version || '' }}
            GITHUB_REPO=${{ github.repository }}
            NONROOT_USER=${{ env.NONROOT_USER }}
            UBUNTU_VERSION=${{ matrix.os.distro }}
          context: docker/ubuntu
          outputs: type=image,name=${{ env.CONTAINER_IMAGE }},push-by-digest=true,name-canonical=true,push=true
          platforms: ${{ matrix.architecture.platform }}
          provenance: mode=max
          push: true
          sbom: true
          tags: ${{ env.CONTAINER_IMAGE }}
          target: ${{ matrix.os.compiler_name }}
